"use strict";
let fruit = "apple";
console.log("Is the fruit == apple?. I predict it is True");
console.log(fruit == "apple");
fruit = "banana";
console.log("\nIs the fruit == apple?. I predict it is False");
console.log(fruit == "apple");
console.log("\nIs the fruit != apple?. I predict it is True");
console.log(fruit != "apple");
let a = 2;
console.log("\nIs a < 3. I predict it is True");
console.log(a < 3);
console.log("\nIs a > 3. I predict it is False");
console.log(a > 3);
console.log("\nIs a <= 3. I predict it is True");
console.log(a <= 3);
console.log("\nIs a >= 3. I predict it is False");
console.log(a >= 3);
